{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4e664456-0b45-45cc-9669-9749a2e46302",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-13 15:45:49.628 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.232 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.235 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.237 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.238 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.362 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2024-10-13 15:45:50.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.428 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.517 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-13 15:45:50.521 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import mysql.connector\n",
    "import streamlit as slt\n",
    "from streamlit_option_menu import option_menu\n",
    "import plotly.express as px\n",
    "import time\n",
    "\n",
    "# Kerala bus\n",
    "lists_k = []\n",
    "df_k = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_k.csv\")\n",
    "for i, r in df_k.iterrows():\n",
    "    lists_k.append(r[\"Route_name\"])\n",
    "\n",
    "lists_T = []\n",
    "df_T = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_T.csv\")\n",
    "for i, r in df_T.iterrows():\n",
    "    lists_T.append(r[\"Route_name\"])\n",
    "\n",
    "lists_b = []\n",
    "df_b = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_B.csv\")\n",
    "for i, r in df_b.iterrows():\n",
    "    lists_b.append(r[\"Route_name\"])\n",
    "\n",
    "# Rajasthan bus\n",
    "lists_R = []\n",
    "df_R = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_R.csv\")\n",
    "for i, r in df_R.iterrows():\n",
    "    lists_R.append(r[\"Route_name\"])\n",
    "\n",
    "# South Bengal bus\n",
    "lists_SB = []\n",
    "df_SB = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_sb.csv\")\n",
    "for i, r in df_SB.iterrows():\n",
    "    lists_SB.append(r[\"Route_name\"])\n",
    "\n",
    "lists_H = []\n",
    "df_H = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_H.csv\")\n",
    "for i, r in df_H.iterrows():\n",
    "    lists_H.append(r[\"Route_name\"])\n",
    "\n",
    "lists_ka = []\n",
    "df_ka = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_ka.csv\")\n",
    "for i, r in df_ka.iterrows():\n",
    "    lists_ka.append(r[\"Route_name\"])\n",
    "\n",
    "# UP bus\n",
    "lists_UP = []\n",
    "df_UP = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_UP.csv\")\n",
    "for i, r in df_UP.iterrows():\n",
    "    lists_UP.append(r[\"Route_name\"])\n",
    "\n",
    "# West Bengal bus\n",
    "lists_WB = []\n",
    "df_WB = pd.read_csv(r\"C:\\Users\\Sivanesh Kumar\\Desktop\\bus details\\df_buses_wb.csv\")\n",
    "for i, r in df_WB.iterrows():\n",
    "    lists_WB.append(r[\"Route_name\"])\n",
    "\n",
    "# Setting up Streamlit page\n",
    "slt.set_page_config(layout=\"wide\")\n",
    "\n",
    "web = option_menu(\n",
    "    menu_title=\"🚌OnlineBus\",\n",
    "    options=[\"Home\", \"📍States and Routes\"],\n",
    "    icons=[\"house\", \"info-circle\"],\n",
    "    orientation=\"horizontal\"\n",
    ")\n",
    "\n",
    "# Home page setting\n",
    "if web == \"Home\":\n",
    "    slt.image(\"https://via.placeholder.com/500x300\", width=200)  # Placeholder image to avoid file not found error\n",
    "    slt.title(\"Redbus Data Scraping with Selenium & Dynamic Filtering using Streamlit\")\n",
    "    slt.subheader(\":blue[Domain:]  Transportation\")\n",
    "    slt.subheader(\":blue[Objective:] \")\n",
    "    slt.markdown(\"The 'Redbus Data Scraping and Filtering with Streamlit Application' aims to revolutionize the transportation industry...\")\n",
    "    slt.subheader(\":blue[Overview:]\")\n",
    "    slt.markdown(\"Selenium: Selenium is a tool used for automating web browsers...\")\n",
    "    slt.markdown(\"Pandas: Pandas helps with data manipulation, cleaning, and preprocessing...\")\n",
    "    slt.markdown(\"MySQL: Using MySQL for database integration and storage...\")\n",
    "    slt.subheader(\":blue[Skill-take:]\")\n",
    "    slt.markdown(\"Selenium, Python, Pandas, MySQL, mysql-connector-python, Streamlit.\")\n",
    "    \n",
    "    \n",
    "# States and Routes page setting\n",
    "if web == \"📍States and Routes\":\n",
    "    S = slt.selectbox(\n",
    "        \"Lists of States\",\n",
    "        [\"Kerala\", \"Andhra \", \"Telangana\", \"kadamba\", \"Rajasthan\", \"southbengal\", \"Himachal\",\"westbengal\",\"Uttar Pradesh\", \"West Bengal\"]\n",
    "    )\n",
    "\n",
    "    col1, col2 = slt.columns(2)\n",
    "    with col1:\n",
    "        select_type = slt.radio(\"Choose bus type\", (\"sleeper\", \"semi-sleeper\", \"others\"))\n",
    "    with col2:\n",
    "        select_fare = slt.radio(\"Choose bus fare range\", (\"50-1000\", \"1000-2000\", \"2000 and above\"))\n",
    "    \n",
    "    # TIME input in Streamlit, convert to string\n",
    "    TIME = slt.time_input(\"Select the time\")\n",
    "    TIME = TIME.strftime(\"%H:%M:%S\")  # Convert time to string format\n",
    "\n",
    "    # Kerala bus fare filtering example\n",
    "    if S == \"Kerala\":\n",
    "        K = slt.selectbox(\"List of routes\", lists_k)\n",
    "\n",
    "        def type_and_fare(bus_type, fare_range):\n",
    "            # MySQL connection setup\n",
    "            conn = mysql.connector.connect(host=\"localhost\", user=\"root\", password=\"1234\", database=\"RED_BUS_DETAILS\")\n",
    "            my_cursor = conn.cursor()\n",
    "\n",
    "            # Define fare range based on the selected input\n",
    "            fare_min, fare_max = (50, 1000) if fare_range == \"50-1000\" else (1000, 2000) if fare_range == \"1000-2000\" else (2000, 100000)\n",
    "\n",
    "            # Define the bus type condition based on user selection\n",
    "            bus_type_condition = {\n",
    "                \"sleeper\": \"Bus_type LIKE '%Sleeper%'\",\n",
    "                \"semi-sleeper\": \"Bus_type LIKE '%A/c Semi Sleeper%'\",\n",
    "                \"others\": \"Bus_type NOT LIKE '%Sleeper%' AND Bus_type NOT LIKE '%Semi-Sleeper%'\"}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ceecf1c-a258-49d3-af1e-f2ef7e6bdbaa",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
